blank_issues_enabled: false
contact_links:
  - name: 🚑 Community support
    url: https://typo3.org/help
    about: Do you have a user or developer question that you think the community can help with? Feel free to ask.
